call next value for hibernate_sequence;
INSERT INTO CATEGORY(`CATEGORY_ID`, `CATEGORY_NAME`,`DEPTH`,`PARENT_ID`) VALUES(1,'외식',1,null);
call next value for hibernate_sequence;
INSERT INTO CATEGORY(CATEGORY_ID, CATEGORY_NAME,DEPTH,PARENT_ID) VALUES(4,'한식',2,1);
call next value for hibernate_sequence;
INSERT INTO CATEGORY(CATEGORY_ID, CATEGORY_NAME,DEPTH,PARENT_ID) VALUES(5,'분식',2,1);
call next value for hibernate_sequence;
INSERT INTO CATEGORY(CATEGORY_ID, CATEGORY_NAME,DEPTH,PARENT_ID) VALUES(6,'중식',2,1);
call next value for hibernate_sequence;
INSERT INTO CATEGORY(CATEGORY_ID, CATEGORY_NAME,DEPTH,PARENT_ID) VALUES(7,'일식',2,1);
call next value for hibernate_sequence;
INSERT INTO CATEGORY(CATEGORY_ID, CATEGORY_NAME,DEPTH,PARENT_ID) VALUES(8,'서양식',2,1);
call next value for hibernate_sequence;
INSERT INTO CATEGORY(CATEGORY_ID, CATEGORY_NAME,DEPTH,PARENT_ID) VALUES(9,'기타외국식',2,1);
call next value for hibernate_sequence;
INSERT INTO CATEGORY(CATEGORY_ID, CATEGORY_NAME,DEPTH,PARENT_ID) VALUES(10,'치킨',2,1);
call next value for hibernate_sequence;
INSERT INTO CATEGORY(CATEGORY_ID, CATEGORY_NAME,DEPTH,PARENT_ID) VALUES(11,'피자',2,1);
call next value for hibernate_sequence;
INSERT INTO CATEGORY(CATEGORY_ID, CATEGORY_NAME,DEPTH,PARENT_ID) VALUES(12,'제과제빵',2,1);
call next value for hibernate_sequence;
INSERT INTO CATEGORY(CATEGORY_ID, CATEGORY_NAME,DEPTH,PARENT_ID) VALUES(13,'아이스크림/빙수',2,1);
call next value for hibernate_sequence;
INSERT INTO CATEGORY(CATEGORY_ID, CATEGORY_NAME,DEPTH,PARENT_ID) VALUES(14,'커피',2,1);
call next value for hibernate_sequence;
INSERT INTO CATEGORY(CATEGORY_ID, CATEGORY_NAME,DEPTH,PARENT_ID) VALUES(15,'음료(커피 외)',2,1);
call next value for hibernate_sequence;
INSERT INTO CATEGORY(CATEGORY_ID, CATEGORY_NAME,DEPTH,PARENT_ID) VALUES(16,'주점',2,1);
call next value for hibernate_sequence;
INSERT INTO CATEGORY(CATEGORY_ID, CATEGORY_NAME,DEPTH,PARENT_ID) VALUES(17,'기타 외식',2,1);

call next value for hibernate_sequence;
INSERT INTO CATEGORY(CATEGORY_ID, CATEGORY_NAME,DEPTH,PARENT_ID) VALUES(2,'도소매',1,null);
call next value for hibernate_sequence;
INSERT INTO CATEGORY(CATEGORY_ID, CATEGORY_NAME,DEPTH,PARENT_ID) VALUES(18,'의류/패션',2,2);
call next value for hibernate_sequence;
INSERT INTO CATEGORY(CATEGORY_ID, CATEGORY_NAME,DEPTH,PARENT_ID) VALUES(19,'화장품',2,2);
call next value for hibernate_sequence;
INSERT INTO CATEGORY(CATEGORY_ID, CATEGORY_NAME,DEPTH,PARENT_ID) VALUES(20,'농수산물',2,2);
call next value for hibernate_sequence;
INSERT INTO CATEGORY(CATEGORY_ID, CATEGORY_NAME,DEPTH,PARENT_ID) VALUES(21,'건강식품',2,2);
call next value for hibernate_sequence;
INSERT INTO CATEGORY(CATEGORY_ID, CATEGORY_NAME,DEPTH,PARENT_ID) VALUES(22,'종합소매점',2,2);
call next value for hibernate_sequence;
INSERT INTO CATEGORY(CATEGORY_ID, CATEGORY_NAME,DEPTH,PARENT_ID) VALUES(23,'기타도소매',2,2);

call next value for hibernate_sequence;
INSERT INTO CATEGORY(CATEGORY_ID, CATEGORY_NAME,DEPTH,PARENT_ID) VALUES(3,'서비스',1,null);
call next value for hibernate_sequence;
INSERT INTO CATEGORY(CATEGORY_ID, CATEGORY_NAME,DEPTH,PARENT_ID) VALUES(24,'교육(교과)',2,3);
call next value for hibernate_sequence;
INSERT INTO CATEGORY(CATEGORY_ID, CATEGORY_NAME,DEPTH,PARENT_ID) VALUES(25,'교육(외국어)',2,3);
call next value for hibernate_sequence;
INSERT INTO CATEGORY(CATEGORY_ID, CATEGORY_NAME,DEPTH,PARENT_ID) VALUES(26,'교육(기타)',2,3);
call next value for hibernate_sequence;
INSERT INTO CATEGORY(CATEGORY_ID, CATEGORY_NAME,DEPTH,PARENT_ID) VALUES(27,'유아 관련',2,3);
call next value for hibernate_sequence;
INSERT INTO CATEGORY(CATEGORY_ID, CATEGORY_NAME,DEPTH,PARENT_ID) VALUES(28,'부동산 중개',2,3);
call next value for hibernate_sequence;
INSERT INTO CATEGORY(CATEGORY_ID, CATEGORY_NAME,DEPTH,PARENT_ID) VALUES(29,'임대',2,3);
call next value for hibernate_sequence;
INSERT INTO CATEGORY(CATEGORY_ID, CATEGORY_NAME,DEPTH,PARENT_ID) VALUES(30,'숙박',2,3);
call next value for hibernate_sequence;
INSERT INTO CATEGORY(CATEGORY_ID, CATEGORY_NAME,DEPTH,PARENT_ID) VALUES(31,'스포츠 관련',2,3);
call next value for hibernate_sequence;
INSERT INTO CATEGORY(CATEGORY_ID, CATEGORY_NAME,DEPTH,PARENT_ID) VALUES(32,'자동차 관련',2,3);
call next value for hibernate_sequence;
INSERT INTO CATEGORY(CATEGORY_ID, CATEGORY_NAME,DEPTH,PARENT_ID) VALUES(33,'PC방',2,3);
call next value for hibernate_sequence;
INSERT INTO CATEGORY(CATEGORY_ID, CATEGORY_NAME,DEPTH,PARENT_ID) VALUES(34,'오락',2,3);
call next value for hibernate_sequence;
INSERT INTO CATEGORY(CATEGORY_ID, CATEGORY_NAME,DEPTH,PARENT_ID) VALUES(35,'배달',2,3);
call next value for hibernate_sequence;
INSERT INTO CATEGORY(CATEGORY_ID, CATEGORY_NAME,DEPTH,PARENT_ID) VALUES(36,'안경',2,3);
call next value for hibernate_sequence;
INSERT INTO CATEGORY(CATEGORY_ID, CATEGORY_NAME,DEPTH,PARENT_ID) VALUES(37,'세탁',2,3);
call next value for hibernate_sequence;
INSERT INTO CATEGORY(CATEGORY_ID, CATEGORY_NAME,DEPTH,PARENT_ID) VALUES(38,'운송',2,3);
call next value for hibernate_sequence;
INSERT INTO CATEGORY(CATEGORY_ID, CATEGORY_NAME,DEPTH,PARENT_ID) VALUES(39,'반려동물',2,3);
call next value for hibernate_sequence;
INSERT INTO CATEGORY(CATEGORY_ID, CATEGORY_NAME,DEPTH,PARENT_ID) VALUES(40,'약국',2,3);
call next value for hibernate_sequence;
INSERT INTO CATEGORY(CATEGORY_ID, CATEGORY_NAME,DEPTH,PARENT_ID) VALUES(41,'기타',2,3);





